Fixed Plugin Conflict
Error: "Legacy XR is currently disabled. Unity has detected that you have one or more XR SDK Provider packages installed. Legacy XR is incompatible with XR SDK. Remove all XR SDK Packages from your project to re-enable legacy XR"

Removed XR Legacy Input Helpers and Updated XR Plugin Management.

This error may actually be a depreciated setting and building the project may actually be fine.